// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJn0BHvKlfwNmWlFO-kcHoP24CIluUX0g',
    appId: '1:919997515366:web:d12f6e1386e46bd1d88fa7',
    messagingSenderId: '919997515366',
    projectId: 'asnanhub-d4902',
    authDomain: 'asnanhub-d4902.firebaseapp.com',
    storageBucket: 'asnanhub-d4902.firebasestorage.app',
    measurementId: 'G-GKKWX2YF1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLCCu590H2iQWPNTgNFx9NtEAyGssjyY',
    appId: '1:919997515366:android:e7422b7dbc01434dd88fa7',
    messagingSenderId: '919997515366',
    projectId: 'asnanhub-d4902',
    storageBucket: 'asnanhub-d4902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjr91DwebVYiXSKIxnJeQait_ARqK1dJE',
    appId: '1:919997515366:ios:b374a1d38c5d8ef4d88fa7',
    messagingSenderId: '919997515366',
    projectId: 'asnanhub-d4902',
    storageBucket: 'asnanhub-d4902.firebasestorage.app',
    iosBundleId: 'com.example.asnanHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjr91DwebVYiXSKIxnJeQait_ARqK1dJE',
    appId: '1:919997515366:ios:b374a1d38c5d8ef4d88fa7',
    messagingSenderId: '919997515366',
    projectId: 'asnanhub-d4902',
    storageBucket: 'asnanhub-d4902.firebasestorage.app',
    iosBundleId: 'com.example.asnanHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJn0BHvKlfwNmWlFO-kcHoP24CIluUX0g',
    appId: '1:919997515366:web:770a7a12aaf97263d88fa7',
    messagingSenderId: '919997515366',
    projectId: 'asnanhub-d4902',
    authDomain: 'asnanhub-d4902.firebaseapp.com',
    storageBucket: 'asnanhub-d4902.firebasestorage.app',
    measurementId: 'G-BJCKHXLPDS',
  );
}
